[package]
name = "chip8"
version = "0.1.0"
authors = ["Alex Friesenhahn"]
edition = "2018"

[dependencies]
log = { version = "0.4.8", features = [ "std" ]}
rand = "0.7.3"
clap = "2.33.0"
sdl2 = { version = "0.33.0", features = [ "gfx" ] }
